version: "3"
services:
  nginx:
    container_name: test_nginx
    image: nginx:latest
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf