version: "3"
services:
  nginx:
    container_name: test_nginx
    image: nginx:latest
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
  node:
    container_name: test_node
    image: node:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./webserver:/mydata
    command:
      - sh
      - -c
      - |
        npm install -g http-server
        cd /mydata
        http-server